from dataclasses import dataclass
from typing import Callable, Optional, Sequence

import jax.numpy as jnp
from jax import Array, enable_x64, jit, lax, random, vmap
from jax.tree_util import Partial
from jax.typing import ArrayLike

from .kernels import matern_3_2
from .priors import Prior


@dataclass
class GP:
    """Gaussian process simulator.

    Args:
        kernel: Kernel function used to build the covariance matrix.
        var: Prior over the marginal variance.
        ls: Prior over the lengthscale.
        period: Optional prior over the period for periodic kernels.
        jitter: Diagonal jitter added before factorization for numerical
            stability.
    """

    kernel: Callable = matern_3_2
    var: Prior = Prior("fixed", {"value": 1})
    ls: Prior = Prior("beta", {"a": 2.5, "b": 6.0})
    period: Optional[Prior] = None
    jitter: float = 1e-5

    def simulate(
        self,
        rng: Array,
        locations: ArrayLike,  # [..., D]
        batch_size: int = 1,
        approx: bool = False,
    ) -> tuple[Array, Array, Array, None | Array, Array]:
        r"""Simulate Gaussian process draws at the requested locations.

        Samples are generated by drawing hyperparameters and standard normal
        noise, then applying a covariance factorization:

        $
        \begin{aligned}
        \mathrm{var}&\sim p_{\mathrm{var}}(\cdot) \\\\
        \mathrm{ls}&\sim p_{\mathrm{ls}}(\cdot) \\\\
        \mathbf{z}&\sim \mathcal{N}(0, I) \\\\
        \mathbf{K}&=k(\mathbf{s}, \mathbf{s}; \mathrm{var}, \mathrm{ls}) \\\\
        \mathbf{f}&=\mathbf{L}\mathbf{z}, \quad \mathbf{L}\mathbf{L}^\top=\mathbf{K}
        \end{aligned}
        $

        When `approx=True`, `L` is built from a Kronecker factorization instead
        of a dense Cholesky decomposition.

        Args:
            rng: Pseudo-random key from `jax.random`.
            locations: Sample locations with shape `[..., D]`.
            batch_size: Number of function draws to generate.
            approx: Whether to use the Kronecker approximation instead of
                dense Cholesky factorization.

        Returns:
            Tuple containing sampled function values, sampled variance,
            sampled lengthscale, sampled period if present, and the standard
            normal draws used to generate the sample.
        """
        locations = locations[:, None] if locations.ndim == 1 else locations
        rng_var, rng_ls, rng_period, rng_z = random.split(rng, 4)
        num_locations = locations.size // locations.shape[-1]
        var = self.var.sample(rng_var)
        ls = self.ls.sample(rng_ls)
        z = random.normal(rng_z, shape=(batch_size, num_locations))
        kernel = self.kernel
        period = None
        if self.period is not None:
            period = self.period.sample(rng_period)
            kernel = Partial(self.kernel, period=period)
        sample = kronecker if approx else cholesky
        with enable_x64():  # TODO(danj): make this optional
            f = sample(kernel, jnp.float64(locations), var, ls, z, self.jitter)
            f = jnp.float32(f)
        f = f.reshape(-1, *locations.shape[:-1], 1)  # batch x grid x 1
        return f, var, ls, period, z


def cholesky(
    kernel: Callable,
    locations: ArrayLike,  # [..., D]
    var: Array,
    ls: Array,
    z: Array,  # [B, L]
    jitter: float = 1e-5,
) -> Array:
    r"""Generate samples using dense Cholesky factorization.

    This computes

    $$
    \mathbf{f} = \mathbf{L}\mathbf{z}, \quad
    \mathbf{L}\mathbf{L}^\top =
    k(\mathbf{s}, \mathbf{s}; \mathrm{var}, \mathrm{ls}) + \epsilon I.
    $$

    Args:
        kernel: Kernel function used to build the covariance matrix.
        locations: Sample locations with shape `[..., D]`.
        var: Variance parameter passed to the kernel.
        ls: Lengthscale parameter passed to the kernel.
        z: Standard normal draws with shape `[B, L]`.
        jitter: Diagonal jitter added before Cholesky decomposition.

    Returns:
        Samples with shape `[B, L]`.
    """
    num_locations = locations.size // locations.shape[-1]
    K = kernel(locations, locations, var, ls) + jitter * jnp.eye(num_locations)
    L = lax.linalg.cholesky(K)
    return jnp.einsum("ij,bj->bi", L, z)


def kronecker(
    kernel: Callable,
    locations: ArrayLike,  # [..., D]
    var: Array,
    ls: Array,
    z: Array,  # [B, L]
    jitter: float = 1e-5,
) -> Array:
    r"""Generate samples using Kronecker covariance factorization.

    This uses a separable approximation in which the covariance factor is
    represented as a Kronecker product of per-axis factors.

    Reference:
        https://proceedings.mlr.press/v37/flaxman15.html

    Args:
        kernel: Kernel function used to build the covariance factors.
        locations: Sample locations with shape `[..., D]`.
        var: Variance parameter passed to the kernel.
        ls: Lengthscale parameter passed to the kernel.
        z: Standard normal draws with shape `[B, L]`.
        jitter: Diagonal jitter added to each factor matrix.

    Returns:
        Samples with shape `[B, L]`.
    """
    Ls = _kronecker_Ls(kernel, locations, var, ls, jitter)
    return vmap(_kronecker_mvprod, in_axes=(None, 0))(Ls, z)


def _kronecker_Ls(
    kernel: Callable,
    locations: ArrayLike,
    var: float,
    ls: float,
    jitter: float = 1e-5,
) -> Sequence[Array]:
    """Compute per-axis Cholesky factors for a separable grid.

    Args:
        kernel: Kernel function used on each axis.
        locations: Grid locations with shape `[..., D]`.
        var: Variance parameter passed to the kernel.
        ls: Lengthscale parameter passed to the kernel.
        jitter: Diagonal jitter added to each axis covariance matrix.

    Returns:
        Cholesky factors for each axis-specific covariance matrix.
    """
    D, Ls = locations.shape[-1], []
    start, stop = jnp.zeros(D, dtype=int), jnp.ones(D, dtype=int)
    for dim, dim_size in enumerate(locations.shape[:-1]):
        _stop = stop.at[dim].set(dim_size)
        axis = lax.slice(locations[..., dim], start, _stop).squeeze()[..., jnp.newaxis]
        K = kernel(axis, axis, var, ls) + jitter * jnp.eye(dim_size)
        Ls += [jnp.linalg.cholesky(K)]
    return Ls


@jit
def _kronecker_mvprod(Ls: Sequence[Array], z: Array) -> Array:
    """Apply a Kronecker product of factors to a vector.

    Reference:
        https://mlg.eng.cam.ac.uk/pub/pdf/Saa11.pdf

    Args:
        Ls: Cholesky factors for each axis-specific covariance matrix.
        z: Vector to multiply by the implicit Kronecker product.

    Returns:
        Product of the Kronecker factorization and `z`.
    """
    x, N = z, z.size
    for L in Ls:
        D = L.shape[0]
        X = x.reshape(D, N // D)
        Z = L @ X
        x = Z.T.flatten()
    return x
